version: '2'
services:
  confluence:
    image: atlassian/confluence
    container_name: confluence
    networks:
      - confluencenet
    volumes:
      - '/b100pro/atlassian/confluence/data:/var/atlassian/application-data/confluence'
      - '/b100pro/atlassian/confluence/conf:/opt/atlassian/confluence/conf'
    ports:
      - '80:8090:8090'
      - '80:8091:8091'
    environment:
      - ATL_PROXY_NAME=wiki.cflm-services.com
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
    restart: unless-stopped
  postgresql:
    image: 'postgres:10.14-alpine'
    container_name: confluence-postgres
    networks:
      - confluencenet
    volumes:
      - '/b100pro/atlassian/confluence/db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=confluencedb
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    restart: unless-stopped
networks:
  confluencenet:
    external: false
